version: '4'
services:
  nginx:
    build: nginx
    container_name: nginx
    depends_on:
      - movim
    hostname: nginx
    restart: always
    env_file:
     - movim.env
    volumes:
     - movim-volume:/var/www/movim:rw
    ports:
     - "80:80"
     - "443:443"
    networks:
     - movim

  movim:
    build: movim
    container_name: movim
    depends_on:
      - postgres
    hostname: movim
    restart: always
    env_file:
     - movim.env
    volumes:
     - movim-volume:/var/www/movim:rw
    networks:
     - movim

  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    restart: always
    env_file:
      - movim.env
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    networks:
     - movim

networks:
  movim:
    driver: "bridge"

volumes:
  movim-volume:
