version: '3'
services:
  movim:
    build: movim
    container_name: movim
    depends_on:
      - postgres
    hostname: movim
    restart: always
    env_file:
     - movim.env
    ports:
     - "9000:9000"
     - "8080:8080"
    networks:
     - movim
    volumes:
     - movim-volume:/var/www/movim:rw

  nginx:
    build: nginx
    container_name: nginx
    depends_on:
      - movim
    hostname: nginx
    restart: always
    env_file:
     - movim.env
    volumes:
     - movim-volume:/var/www/movim:rw
    ports:
     - "80:80"
     - "443:443"
    networks:
     - movim

  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    restart: always
    env_file:
      - movim.env
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    networks:
     - movim

networks:
  movim:
    driver: "bridge"

volumes:
  movim-volume:
